# Auto-report action script, 3 times a day

name: Auto-report action

on:
  push:
    branches:
      - master
  schedule:
    - cron: '46 0,8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
      run: |
        stuid=( $STUID )
        password=( $PASSWORD )
        python report.py --stuid "${stuid[@]}" --password "${password[@]}"